[phases.setup]
nixPkgs = [
  "ffmpeg",
  "python312",
  "gcc",
  "libffi",
  "zlib"
]

[phases.build]
cmds = [
  "ffmpeg -version",
  "which ffmpeg",
  "python -V",
  "pip install -r requirements.txt"
]
