# sm/dsp/primitives.py

from __future__ import annotations

from typing import Dict, List

from ..enums import RoleName
from .contracts import DSPPrimitiveSpec


def _spec(
    primitive_name: str,
    primitive_class: str,
    path_type: str,
    band_scope: str,
    channel_scope: str,
    detector_mode: str,
    phase_policy: str,
    legal_roles: List[RoleName],
    safety_tags: List[str],
    *,
    min_amount: float = 0.0,
    default_amount: float = 0.0,
    max_amount: float = 1.0,
    min_blend: float = 0.0,
    default_blend: float = 0.0,
    max_blend: float = 1.0,
    min_gain_db: float = -12.0,
    default_gain_db: float = 0.0,
    max_gain_db: float = 12.0,
    min_freq_hz: float = 20.0,
    max_freq_hz: float = 20000.0,
    min_q: float = 0.1,
    max_q: float = 8.0,
    min_attack_ms: float = 0.1,
    max_attack_ms: float = 500.0,
    min_release_ms: float = 1.0,
    max_release_ms: float = 5000.0,
    notes: List[str] | None = None,
) -> DSPPrimitiveSpec:
    return DSPPrimitiveSpec(
        primitive_name=primitive_name,
        primitive_class=primitive_class,
        path_type=path_type,
        band_scope=band_scope,
        channel_scope=channel_scope,
        detector_mode=detector_mode,
        phase_policy=phase_policy,
        legal_roles=legal_roles,
        safety_tags=safety_tags,
        min_amount=min_amount,
        default_amount=default_amount,
        max_amount=max_amount,
        min_blend=min_blend,
        default_blend=default_blend,
        max_blend=max_blend,
        min_gain_db=min_gain_db,
        default_gain_db=default_gain_db,
        max_gain_db=max_gain_db,
        min_freq_hz=min_freq_hz,
        max_freq_hz=max_freq_hz,
        min_q=min_q,
        max_q=max_q,
        min_attack_ms=min_attack_ms,
        max_attack_ms=max_attack_ms,
        min_release_ms=min_release_ms,
        max_release_ms=max_release_ms,
        notes=notes or [],
    )


PRIMITIVE_REGISTRY: Dict[str, DSPPrimitiveSpec] = {
    # ---------------------------------------------------------
    # Corrective primitives
    # ---------------------------------------------------------
    "dynamic_bell_cut": _spec(
        primitive_name="dynamic_bell_cut",
        primitive_class="dynamic_eq_cut",
        path_type="inplace",
        band_scope="cleanup_zone",
        channel_scope="stereo",
        detector_mode="band_envelope",
        phase_policy="minimum",
        legal_roles=[RoleName.CLEANUP, RoleName.GUARD],
        safety_tags=["body_sensitive", "bridge_sensitive"],
        min_amount=0.05,
        default_amount=0.26,
        max_amount=0.72,
        min_gain_db=-4.0,
        default_gain_db=-1.1,
        max_gain_db=0.0,
        min_freq_hz=140.0,
        max_freq_hz=5200.0,
        min_q=0.35,
        max_q=2.80,
        min_attack_ms=4.0,
        max_attack_ms=120.0,
        min_release_ms=25.0,
        max_release_ms=450.0,
        notes=[
            "Primary cleanup primitive.",
            "Use before any support restoration.",
            "Should not create body holes.",
        ],
    ),
    "dynamic_wide_cut": _spec(
        primitive_name="dynamic_wide_cut",
        primitive_class="dynamic_eq_wide_cut",
        path_type="inplace",
        band_scope="cleanup_zone",
        channel_scope="stereo",
        detector_mode="envelope",
        phase_policy="minimum",
        legal_roles=[RoleName.CLEANUP],
        safety_tags=["body_sensitive", "bridge_sensitive"],
        min_amount=0.05,
        default_amount=0.22,
        max_amount=0.62,
        min_gain_db=-3.5,
        default_gain_db=-0.9,
        max_gain_db=0.0,
        min_freq_hz=170.0,
        max_freq_hz=900.0,
        min_q=0.20,
        max_q=1.10,
        min_attack_ms=6.0,
        max_attack_ms=160.0,
        min_release_ms=35.0,
        max_release_ms=500.0,
        notes=[
            "Broad mud/buildup restraint.",
            "Never substitute for narrow harsh control.",
        ],
    ),
    "restrained_static_cut": _spec(
        primitive_name="restrained_static_cut",
        primitive_class="static_eq_cut",
        path_type="inplace",
        band_scope="cleanup_zone",
        channel_scope="stereo",
        detector_mode="none",
        phase_policy="minimum",
        legal_roles=[RoleName.CLEANUP, RoleName.GUARD],
        safety_tags=["body_sensitive"],
        min_amount=0.02,
        default_amount=0.14,
        max_amount=0.34,
        min_gain_db=-2.5,
        default_gain_db=-0.5,
        max_gain_db=0.0,
        min_freq_hz=180.0,
        max_freq_hz=4800.0,
        min_q=0.35,
        max_q=2.20,
        notes=[
            "Only for mild contour correction.",
            "Should not be the main cleanup tool on complex material.",
        ],
    ),
    "dynamic_tilt_down": _spec(
        primitive_name="dynamic_tilt_down",
        primitive_class="dynamic_tilt",
        path_type="inplace",
        band_scope="full",
        channel_scope="stereo",
        detector_mode="envelope",
        phase_policy="mixed",
        legal_roles=[RoleName.CLEANUP],
        safety_tags=["body_sensitive", "top_sensitive"],
        min_amount=0.02,
        default_amount=0.10,
        max_amount=0.26,
        min_gain_db=-2.5,
        default_gain_db=-0.35,
        max_gain_db=0.0,
        min_freq_hz=350.0,
        max_freq_hz=4000.0,
        notes=[
            "Use only when buildup behaves as broad tonal skew.",
            "Not a replacement for specific dynamic cuts.",
        ],
    ),
    "local_antiharsh_control": _spec(
        primitive_name="local_antiharsh_control",
        primitive_class="dynamic_harsh_control",
        path_type="inplace",
        band_scope="presence",
        channel_scope="stereo",
        detector_mode="band_envelope",
        phase_policy="minimum",
        legal_roles=[RoleName.CLEANUP, RoleName.PROJECTION],
        safety_tags=["top_sensitive"],
        min_amount=0.04,
        default_amount=0.18,
        max_amount=0.44,
        min_gain_db=-3.0,
        default_gain_db=-0.7,
        max_gain_db=0.0,
        min_freq_hz=2200.0,
        max_freq_hz=6200.0,
        min_q=0.45,
        max_q=2.60,
        min_attack_ms=1.0,
        max_attack_ms=50.0,
        min_release_ms=15.0,
        max_release_ms=240.0,
        notes=[
            "Harshness restraint, not broad presence removal.",
        ],
    ),
        "local_desibilance_control": _spec(
        primitive_name="local_desibilance_control",
        primitive_class="dynamic_sibilance_control",
        path_type="finish",
        band_scope="top",
        channel_scope="stereo",
        detector_mode="band_envelope",
        phase_policy="minimum",
        legal_roles=[RoleName.SPARK],
        safety_tags=["top_sensitive", "finish_sensitive"],
        min_amount=0.04,
        default_amount=0.16,
        max_amount=0.40,
        min_gain_db=-3.5,
        default_gain_db=-0.8,
        max_gain_db=0.0,
        min_freq_hz=4500.0,
        max_freq_hz=11000.0,
        min_q=0.60,
        max_q=3.20,
        min_attack_ms=0.5,
        max_attack_ms=18.0,
        min_release_ms=12.0,
        max_release_ms=180.0,
        notes=[
            "Finish-local top safety restraint.",
            "Used only inside spark finish layer in V1.",
        ],
    ),

    # ---------------------------------------------------------
    # Support primitives
    # ---------------------------------------------------------
    "controlled_bell_boost": _spec(
        primitive_name="controlled_bell_boost",
        primitive_class="support_eq_boost",
        path_type="parallel",
        band_scope="low_body",
        channel_scope="stereo",
        detector_mode="none",
        phase_policy="minimum",
        legal_roles=[RoleName.ANCHOR],
        safety_tags=["body_sensitive"],
        min_amount=0.04,
        default_amount=0.18,
        max_amount=0.42,
        min_blend=0.01,
        default_blend=0.08,
        max_blend=0.24,
        min_gain_db=0.0,
        default_gain_db=0.8,
        max_gain_db=2.5,
        min_freq_hz=120.0,
        max_freq_hz=360.0,
        min_q=0.30,
        max_q=1.60,
        notes=[
            "Supportive body fill, not mud restoration.",
        ],
    ),
    "dynamic_body_support_boost": _spec(
        primitive_name="dynamic_body_support_boost",
        primitive_class="dynamic_support_boost",
        path_type="parallel",
        band_scope="low_body",
        channel_scope="stereo",
        detector_mode="band_envelope",
        phase_policy="minimum",
        legal_roles=[RoleName.ANCHOR],
        safety_tags=["body_sensitive"],
        min_amount=0.04,
        default_amount=0.16,
        max_amount=0.38,
        min_blend=0.01,
        default_blend=0.07,
        max_blend=0.18,
        min_gain_db=0.0,
        default_gain_db=0.7,
        max_gain_db=2.2,
        min_freq_hz=130.0,
        max_freq_hz=340.0,
        min_q=0.35,
        max_q=1.80,
        min_attack_ms=8.0,
        max_attack_ms=120.0,
        min_release_ms=40.0,
        max_release_ms=500.0,
        notes=[
            "Adaptive body reinforcement.",
            "Use when body exists but needs support, not rescue-by-hype.",
        ],
    ),
    "restrained_parallel_fill": _spec(
        primitive_name="restrained_parallel_fill",
        primitive_class="parallel_fill",
        path_type="parallel",
        band_scope="low_body",
        channel_scope="stereo",
        detector_mode="none",
        phase_policy="mixed",
        legal_roles=[RoleName.ANCHOR],
        safety_tags=["body_sensitive", "delivery_sensitive"],
        min_amount=0.02,
        default_amount=0.12,
        max_amount=0.30,
        min_blend=0.01,
        default_blend=0.06,
        max_blend=0.14,
        min_gain_db=0.0,
        default_gain_db=0.6,
        max_gain_db=1.8,
        min_freq_hz=110.0,
        max_freq_hz=420.0,
        min_q=0.20,
        max_q=1.20,
        notes=[
            "Broad parallel body bed.",
            "Keep conservative to avoid cleanup cancellation.",
        ],
    ),
    "restrained_parallel_handoff_support": _spec(
        primitive_name="restrained_parallel_handoff_support",
        primitive_class="parallel_handoff_support",
        path_type="parallel",
        band_scope="bridge",
        channel_scope="stereo",
        detector_mode="none",
        phase_policy="mixed",
        legal_roles=[RoleName.BRIDGE],
        safety_tags=["bridge_sensitive", "body_sensitive"],
        min_amount=0.03,
        default_amount=0.15,
        max_amount=0.34,
        min_blend=0.01,
        default_blend=0.07,
        max_blend=0.18,
        min_gain_db=0.0,
        default_gain_db=0.7,
        max_gain_db=2.0,
        min_freq_hz=140.0,
        max_freq_hz=520.0,
        min_q=0.25,
        max_q=1.50,
        notes=[
            "Supports bass-to-body and body-to-mid glue.",
        ],
    ),
    "transient_safe_support_compression": _spec(
        primitive_name="transient_safe_support_compression",
        primitive_class="support_compression",
        path_type="parallel",
        band_scope="bridge",
        channel_scope="stereo",
        detector_mode="rms",
        phase_policy="mixed",
        legal_roles=[RoleName.BRIDGE],
        safety_tags=["bridge_sensitive", "delivery_sensitive"],
        min_amount=0.02,
        default_amount=0.10,
        max_amount=0.24,
        min_blend=0.01,
        default_blend=0.05,
        max_blend=0.12,
        min_gain_db=-2.0,
        default_gain_db=0.0,
        max_gain_db=1.2,
        min_freq_hz=70.0,
        max_freq_hz=450.0,
        min_attack_ms=12.0,
        max_attack_ms=80.0,
        min_release_ms=60.0,
        max_release_ms=350.0,
        notes=[
            "Only when bridge needs stabilization, never for obvious glue hype.",
        ],
    ),

    # ---------------------------------------------------------
    # Projection primitives
    # ---------------------------------------------------------
    "broad_presence_contour": _spec(
        primitive_name="broad_presence_contour",
        primitive_class="presence_contour",
        path_type="inplace",
        band_scope="presence",
        channel_scope="mid",
        detector_mode="none",
        phase_policy="minimum",
        legal_roles=[RoleName.PROJECTION],
        safety_tags=["top_sensitive"],
        min_amount=0.04,
        default_amount=0.18,
        max_amount=0.38,
        min_gain_db=0.0,
        default_gain_db=0.7,
        max_gain_db=1.8,
        min_freq_hz=1100.0,
        max_freq_hz=4200.0,
        min_q=0.20,
        max_q=1.30,
        notes=[
            "Primary forward contour primitive.",
            "Prefer broad shaping over edgy peaks.",
        ],
    ),
    "dynamic_presence_lift": _spec(
        primitive_name="dynamic_presence_lift",
        primitive_class="dynamic_presence_boost",
        path_type="inplace",
        band_scope="presence",
        channel_scope="mid",
        detector_mode="band_envelope",
        phase_policy="minimum",
        legal_roles=[RoleName.PROJECTION],
        safety_tags=["top_sensitive", "body_sensitive"],
        min_amount=0.04,
        default_amount=0.16,
        max_amount=0.34,
        min_gain_db=0.0,
        default_gain_db=0.6,
        max_gain_db=1.6,
        min_freq_hz=1400.0,
        max_freq_hz=5000.0,
        min_q=0.30,
        max_q=1.80,
        min_attack_ms=5.0,
        max_attack_ms=100.0,
        min_release_ms=30.0,
        max_release_ms=320.0,
        notes=[
            "Adaptive forwardness support.",
            "Must stay under top safety laws.",
        ],
    ),
    "band_limited_soft_saturation": _spec(
        primitive_name="band_limited_soft_saturation",
        primitive_class="band_limited_saturation",
        path_type="parallel",
        band_scope="presence",
        channel_scope="mid",
        detector_mode="none",
        phase_policy="mixed",
        legal_roles=[RoleName.PROJECTION],
        safety_tags=["top_sensitive", "delivery_sensitive"],
        min_amount=0.03,
        default_amount=0.14,
        max_amount=0.30,
        min_blend=0.01,
        default_blend=0.05,
        max_blend=0.12,
        min_gain_db=0.0,
        default_gain_db=0.5,
        max_gain_db=1.5,
        min_freq_hz=1200.0,
        max_freq_hz=5200.0,
        notes=[
            "Density, not brightness.",
            "Should be followed or bounded by local de-harsh logic.",
        ],
    ),
    "controlled_harmonic_density": _spec(
        primitive_name="controlled_harmonic_density",
        primitive_class="harmonic_density",
        path_type="parallel",
        band_scope="presence",
        channel_scope="mid",
        detector_mode="none",
        phase_policy="mixed",
        legal_roles=[RoleName.PROJECTION],
        safety_tags=["top_sensitive", "delivery_sensitive"],
        min_amount=0.03,
        default_amount=0.12,
        max_amount=0.28,
        min_blend=0.01,
        default_blend=0.04,
        max_blend=0.10,
        min_gain_db=0.0,
        default_gain_db=0.4,
        max_gain_db=1.2,
        min_freq_hz=1500.0,
        max_freq_hz=6000.0,
        notes=[
            "Projection assist layer.",
            "Never a substitute for contour-based projection.",
        ],
    ),
    "projection_local_deharsh": _spec(
        primitive_name="projection_local_deharsh",
        primitive_class="projection_safety_control",
        path_type="inplace",
        band_scope="presence",
        channel_scope="mid",
        detector_mode="band_envelope",
        phase_policy="minimum",
        legal_roles=[RoleName.PROJECTION],
        safety_tags=["top_sensitive"],
        min_amount=0.03,
        default_amount=0.12,
        max_amount=0.30,
        min_gain_db=-2.5,
        default_gain_db=-0.5,
        max_gain_db=0.0,
        min_freq_hz=2200.0,
        max_freq_hz=6500.0,
        min_q=0.45,
        max_q=2.80,
        min_attack_ms=1.0,
        max_attack_ms=30.0,
        min_release_ms=12.0,
        max_release_ms=180.0,
        notes=[
            "Safety primitive for projection layer.",
        ],
    ),

    # ---------------------------------------------------------
    # Finish primitives
    # ---------------------------------------------------------
    "micro_air_shelf": _spec(
        primitive_name="micro_air_shelf",
        primitive_class="air_shelf",
        path_type="finish",
        band_scope="top",
        channel_scope="stereo",
        detector_mode="none",
        phase_policy="minimum",
        legal_roles=[RoleName.SPARK],
        safety_tags=["top_sensitive", "finish_sensitive", "delivery_sensitive"],
        min_amount=0.01,
        default_amount=0.08,
        max_amount=0.18,
        min_blend=0.01,
        default_blend=0.04,
        max_blend=0.08,
        min_gain_db=0.0,
        default_gain_db=0.35,
        max_gain_db=1.0,
        min_freq_hz=7000.0,
        max_freq_hz=18000.0,
        min_q=0.20,
        max_q=0.90,
        notes=[
            "Finish-only air polish.",
            "Never use to create fake projection.",
        ],
    ),
    "micro_top_texture": _spec(
        primitive_name="micro_top_texture",
        primitive_class="top_texture",
        path_type="finish",
        band_scope="top",
        channel_scope="stereo",
        detector_mode="none",
        phase_policy="mixed",
        legal_roles=[RoleName.SPARK],
        safety_tags=["top_sensitive", "finish_sensitive"],
        min_amount=0.01,
        default_amount=0.06,
        max_amount=0.16,
        min_blend=0.01,
        default_blend=0.03,
        max_blend=0.07,
        min_gain_db=0.0,
        default_gain_db=0.25,
        max_gain_db=0.8,
        min_freq_hz=5500.0,
        max_freq_hz=16000.0,
        notes=[
            "Very light top texture enhancement.",
        ],
    ),
    "protected_high_side_polish": _spec(
        primitive_name="protected_high_side_polish",
        primitive_class="side_top_polish",
        path_type="finish",
        band_scope="top",
        channel_scope="side",
        detector_mode="none",
        phase_policy="minimum",
        legal_roles=[RoleName.SPARK],
        safety_tags=["width_sensitive", "top_sensitive", "finish_sensitive"],
        min_amount=0.01,
        default_amount=0.05,
        max_amount=0.12,
        min_blend=0.01,
        default_blend=0.02,
        max_blend=0.05,
        min_gain_db=0.0,
        default_gain_db=0.2,
        max_gain_db=0.7,
        min_freq_hz=6500.0,
        max_freq_hz=18000.0,
        notes=[
            "High-side polish only.",
            "Must be correlation-safe.",
        ],
    ),
    "micro_width_high_only": _spec(
        primitive_name="micro_width_high_only",
        primitive_class="high_only_width",
        path_type="finish",
        band_scope="top",
        channel_scope="side",
        detector_mode="none",
        phase_policy="mixed",
        legal_roles=[RoleName.SPARK],
        safety_tags=["width_sensitive", "finish_sensitive", "delivery_sensitive"],
        min_amount=0.01,
        default_amount=0.04,
        max_amount=0.10,
        min_blend=0.01,
        default_blend=0.02,
        max_blend=0.05,
        min_gain_db=0.0,
        default_gain_db=0.0,
        max_gain_db=0.5,
        min_freq_hz=7000.0,
        max_freq_hz=20000.0,
        notes=[
            "Width only in protected high band.",
            "Never touches foundation or body domain.",
        ],
    ),

    # ---------------------------------------------------------
    # Delivery primitives
    # ---------------------------------------------------------
    "output_gain_trim": _spec(
        primitive_name="output_gain_trim",
        primitive_class="output_trim",
        path_type="delivery",
        band_scope="full",
        channel_scope="stereo",
        detector_mode="none",
        phase_policy="mixed",
        legal_roles=[],
        safety_tags=["delivery_sensitive"],
        min_amount=0.01,
        default_amount=0.10,
        max_amount=0.40,
        min_gain_db=-6.0,
        default_gain_db=-0.3,
        max_gain_db=1.0,
        notes=[
            "Final output level discipline.",
        ],
    ),
    "true_peak_limiter": _spec(
        primitive_name="true_peak_limiter",
        primitive_class="true_peak_limiter",
        path_type="delivery",
        band_scope="full",
        channel_scope="stereo",
        detector_mode="peak",
        phase_policy="mixed",
        legal_roles=[],
        safety_tags=["delivery_sensitive", "top_sensitive"],
        min_amount=0.05,
        default_amount=0.18,
        max_amount=0.42,
        min_blend=1.0,
        default_blend=1.0,
        max_blend=1.0,
        min_gain_db=-6.0,
        default_gain_db=-1.0,
        max_gain_db=0.0,
        min_attack_ms=0.1,
        max_attack_ms=20.0,
        min_release_ms=5.0,
        max_release_ms=300.0,
        notes=[
            "Final ceiling protector.",
            "Protects output, does not redesign mix/master tone.",
        ],
    ),
    "safety_ceiling_trim": _spec(
        primitive_name="safety_ceiling_trim",
        primitive_class="ceiling_trim",
        path_type="delivery",
        band_scope="full",
        channel_scope="stereo",
        detector_mode="none",
        phase_policy="mixed",
        legal_roles=[],
        safety_tags=["delivery_sensitive"],
        min_amount=0.01,
        default_amount=0.08,
        max_amount=0.24,
        min_gain_db=-3.0,
        default_gain_db=-0.5,
        max_gain_db=0.0,
        notes=[
            "Emergency ceiling headroom trim.",
        ],
    ),
    "final_balance_guard": _spec(
        primitive_name="final_balance_guard",
        primitive_class="final_balance_guard",
        path_type="delivery",
        band_scope="full",
        channel_scope="stereo",
        detector_mode="envelope",
        phase_policy="mixed",
        legal_roles=[],
        safety_tags=["delivery_sensitive", "body_sensitive", "top_sensitive"],
        min_amount=0.01,
        default_amount=0.05,
        max_amount=0.16,
        min_gain_db=-1.5,
        default_gain_db=0.0,
        max_gain_db=0.5,
        notes=[
            "Last-stage micro-guard against output imbalance.",
            "Should stay extremely conservative.",
        ],
    ),
}


def get_primitive_spec(primitive_name: str) -> DSPPrimitiveSpec:
    if primitive_name not in PRIMITIVE_REGISTRY:
        raise KeyError(f"Unknown DSP primitive: {primitive_name}")
    return PRIMITIVE_REGISTRY[primitive_name]


def has_primitive(primitive_name: str) -> bool:
    return primitive_name in PRIMITIVE_REGISTRY


def list_primitive_names() -> List[str]:
    return list(PRIMITIVE_REGISTRY.keys())


def list_primitive_specs() -> List[DSPPrimitiveSpec]:
    return list(PRIMITIVE_REGISTRY.values())


def list_primitives_for_role(role: RoleName) -> List[DSPPrimitiveSpec]:
    return [
        spec
        for spec in PRIMITIVE_REGISTRY.values()
        if role in spec.legal_roles
    ]


def list_primitives_for_path_type(path_type: str) -> List[DSPPrimitiveSpec]:
    return [
        spec
        for spec in PRIMITIVE_REGISTRY.values()
        if spec.path_type == path_type
    ]


def list_primitives_by_class(primitive_class: str) -> List[DSPPrimitiveSpec]:
    return [
        spec
        for spec in PRIMITIVE_REGISTRY.values()
        if spec.primitive_class == primitive_class
    ]
